### ISSUE TITLE
Upgrade Rails to 5.0

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/rest-whois#85]
## Task list is still incomplete, but that's enough to get the test suite to run with limited success.
As a small project, this one can be our pilot for upgrade to Rails 5.x. Provisional upgrade task are:

- [x] Remove `config.active_record.raise_in_transactional_callbacks = true`
- [x] Rename `use_transactional_fixtures = true` to `use_transactional_tests = true`
- [x] Fix occurences of ActionView::Template::Error: unable to convert unpermitted parameters to hash
- [x] Fix keyword argument error in get method (`get '/v1/privatedomain.test', format: :json`)
- [x] Create `ApplicationRecord` superclass
- [x] Convert inheritance from `ActiveRecord::Base` to `ApplicationRecord`
- [ ] Investigate secrets/encrypted secrets changes, as those are introduced in Rails 5.0, and then significantly changed in Rais 5.1

**Comment by artur-beljajev** [comment]
In addition to what is already mentioned: perhaps we could either run `rails app:update` on the existing app or generate new Rails 5 app and compare the difference?

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#the-update-task

**Comment by maciej-szlosarczyk** [comment]
@artur-beljajev, I just did that.

The main difference was the addition of `config/secrets.yml`, I already added an item to the list for that.

```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04eff22c7562364e668b9a73de7367377d4fcae3ecf0f95d87f0e498f313d269d5e1b90cafac0f3b6b4114fc127e96994d476bc680195cdc85dca9cce6dfc0e8

test:
  secret_key_base: ed852353e990ec65b438038a508c450ad52297641762ac94a3714ba18de67a5eff73e05a13b58fb1f38b3965a9cdffbdb2dc6e29be88d68bb4b2921eb489c878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

**Comment by maciej-szlosarczyk** [comment]
I'd ask the reverse: Do we need Figaro (or any other third-party gem) to provide the same functionality that is/will be baked into Rails?

In any case, that's an item for research and discussion, not an actual task to implement just yet.

**Comment by artur-beljajev** [comment]
+1 for using a solution from Rails, if possible.

**Comment by vohmar** [comment]
* contact request - email verification form (/contact_requests/new): changing language returns error 500.

**Comment by maciej-szlosarczyk** [comment]
Now the issue is fixed. Copying my comment from the pull request:

config.serve_static_files becomes config.public_file_server.enabled
config.static_cache_control becomes config.public_file_server.headers

Values stay the same, only change is in naming of variables. They're located in `config/environments/production.rb`.

**Comment by vohmar** [comment]
secret/encrypted secrets is for rails 5.2. As 5.0 is now in production I will close this one.
